apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: uvindu-key-vault
spec:
  provider: azure
  parameters:
    keyvaultName: "uvindu-key-vault"       
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: "953129a2-f0e0-48a4-a530-fe5250495dbe"                      
    objects:  |
      array:
        - |
          objectName: ExampleSecret       # In this example, 'ExampleSecret'   
          objectType: secret              # Object types: secret, key or cert
    tenantId: "da76d684-740f-4d94-8717-9d5fb21dd1f9" 